name: asset_pack
description: Asset Management Library for Dart Games
version: 0.6.2
authors:
- John McCutchan <john@johnmccutchan.com>
description: Asset Management Library for Dart Games
homepage: https://github.com/johnmccutchan/asset_pack
dev_dependencies:
  unittest: any
  browser: any
  hop: any
  path: any
